/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gjj_main_NdkUtils */

#ifndef _Included_com_gjj_main_NdkUtils
#define _Included_com_gjj_main_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gjj_main_NdkUtils
 * Method:    getNdkString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gjj_main_NdkUtils_getNdkString
  (JNIEnv *, jclass);

/*
 * Class:     com_gjj_main_NdkUtils
 * Method:    getNdkTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gjj_main_NdkUtils_getNdkTitle
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
